version: '3'
services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: ineuc-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"